version: '3.8'
services:
  # 1. App Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mymy-demo-image
    container_name: mymy-demo-container
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  # 2. Web Server (Nginx)
  nginx:
    image: nginx:alpine
    container_name: mymy-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker-config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  # 3. Database (MySQL)
  db:
    image: mysql:8.0
    container_name: mymy-db
    environment:
      MYSQL_DATABASE: mymy_demo
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
